### ISSUE TITLE
mod_geoip2 segfaults Apache childs if MPM event is used and GeoIPScanProxyHeaders is enabled

### ISSUE THREAD

**Issue by jnk0** [maxmind/geoip-api-mod_geoip2#24] opened 2016-11-14 13:05 UTC
When activating mod_geoip2 feature GeoIPScanProxyHeaders it crashes all Apache childs if the MPM event is used. When using MPM prefork or worker everything works as expected.

How to reproduce:
- Configure httpd to use MPM event
- Enable GeoIPScanProxyHeaders

The following errors are listed in error_log:

> [Sat Nov 12 21:11:03.240327 2016] [core:notice] [pid 12229:tid 139992215623744] AH00052: child pid 21339 exit signal Segmentation fault (11)
[Sat Nov 12 21:11:03.240387 2016] [core:notice] [pid 12229:tid 139992215623744] AH00052: child pid 21340 exit signal Segmentation fault (11)
[Sat Nov 12 21:11:13.251891 2016] [core:notice] [pid 12229:tid 139992215623744] AH00052: child pid 21409 exit signal Segmentation fault (11)
[Sat Nov 12 21:11:13.251933 2016] [core:notice] [pid 12229:tid 139992215623744] AH00052: child pid 21410 exit signal Segmentation fault (11)
[Sat Nov 12 21:11:24.265948 2016] [core:notice] [pid 12229:tid 139992215623744] AH00052: child pid 21479 exit signal Segmentation fault (11)
[Sat Nov 12 21:11:24.265998 2016] [core:notice] [pid 12229:tid 139992215623744] AH00052: child pid 21514 exit signal Segmentation fault (11)
[Sat Nov 12 21:11:35.278927 2016] [core:notice] [pid 12229:tid 139992215623744] AH00052: child pid 21572 exit signal Segmentation fault (11)
[Sat Nov 12 21:11:35.278967 2016] [core:notice] [pid 12229:tid 139992215623744] AH00052: child pid 21607 exit signal Segmentation fault (11)
[Sat Nov 12 21:11:46.292560 2016] [core:notice] [pid 12229:tid 139992215623744] AH00052: child pid 21642 exit signal Segmentation fault (11)
[Sat Nov 12 21:11:46.292616 2016] [core:notice] [pid 12229:tid 139992215623744] AH00052: child pid 21677 exit signal Segmentation fault (11)
[Sat Nov 12 21:11:57.307003 2016] [core:notice] [pid 12229:tid 139992215623744] AH00052: child pid 21713 exit signal Segmentation fault (11)
[Sat Nov 12 21:11:57.307044 2016] [core:notice] [pid 12229:tid 139992215623744] AH00052: child pid 21748 exit signal Segmentation fault (11)
[Sat Nov 12 21:12:08.320456 2016] [core:notice] [pid 12229:tid 139992215623744] AH00052: child pid 21783 exit signal Segmentation fault (11)
[Sat Nov 12 21:12:08.320509 2016] [core:notice] [pid 12229:tid 139992215623744] AH00052: child pid 21819 exit signal Segmentation fault (11)

Used Software: CentOS 7.2, Apache/2.4.6 (CentOS), mod_geoip 1.2.10 from EPEL repository

**Comment by oschwald** [comment] 2016-11-21 20:11
Does this happen for every request? I attempted to reproduce this locally but I am having problems replicating it. Is there any chance you could generate a core dump and then a stack trace in `gdb`?

**Comment by oschwald** [comment] 2019-07-03 21:51
Closing due to lack of information.

**Closed by oschwald** 2019-07-03 21:51 UTC
